build:
	g++ -o game test.cpp perlin.cpp -I/opt/homebrew/include -L/opt/homebrew/lib -lraylib -lm -ldl -lpthread -framework OpenGL -framework Cocoa -framework IOKit -std=c++17
run: 
	./game

clean:
	rm game
